### ISSUE TITLE
Panel Loses Content

### ISSUE THREAD

**Issue by sachnk** [mathuo/dockview#472] opened 2024-01-23 02:17 UTC
**Describe the bug**
When closing a panel in a group, the content of other panels within the group is seemingly lost. This appears to happen with version 1.9.0 and up. This is happening after I upgraded to 1.9.0. When I downgrade to 1.8.5, the problem goes away.

**To Reproduce**
Here's a [sandbox](https://codesandbox.io/p/sandbox/youthful-dream-j9zfrn) that reproduces this. This fork only modifies the content of the panel -- it simply adds "HELLO" to each panel. 

1. Go to [sandbox](https://codesandbox.io/p/sandbox/youthful-dream-j9zfrn)
2. Close 'Panel 1'
3. See the "HELLO" text disappear on other panels within that group

**Expected behavior**
Content within a group should not be impacted by closing panels in that group.

**Screenshots**
![dockview-bug](https://github.com/mathuo/dockview/assets/5503945/64b7517b-0dae-4fc0-9f9c-6299bd66ab2c)

**Desktop (please complete the following information):**
 Chrome
 
 119.0.6045.199

**Additional context**

**Comment by mathuo** [comment] 2024-01-23 17:31
Sorry, this seems to be caused by changes to the rendering logic in `1.9.0` to handle multiple types of rendering options and has somehow slipped past the testing stage.

I will patch this today and get a `1.9.3` out.

PR raised [here](https://github.com/mathuo/dockview/pull/474) with a fix and tests, the documenation will be updated to render content in the panel to make this easier to spot too.

![image](https://github.com/mathuo/dockview/assets/6710312/8768ea84-e272-46d7-9ab4-583800e0bf4a)

**Comment by mathuo** [comment] 2024-01-23 18:45
@sachnk  Fix released in version 1.9.2

Thanks for the issue report! Hopefully all is fixed for you now.

**Closed by mathuo** 2024-01-23 18:45 UTC

**Comment by sachnk** [comment] 2024-01-24 15:04
> @sachnk Fix released in version 1.9.2
> 
> Thanks for the issue report! Hopefully all is fixed for you now.

Yep, all good now... thanks for the quick turn around!
